# Generated by Django 5.2.11 on 2026-02-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="顧客番号"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="氏名")),
                (
                    "name_kana",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="氏名（カナ）"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
                ),
                ("address1", models.CharField(max_length=255, verbose_name="住所1")),
                (
                    "address2",
                    models.CharField(blank=True, max_length=255, verbose_name="住所2"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "billing_method",
                    models.CharField(
                        choices=[
                            ("cash", "現金"),
                            ("bank_transfer", "振込"),
                            ("account_transfer", "口座振替"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="支払方法",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_name",
                    models.CharField(max_length=100, verbose_name="プラン名"),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本料金"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="従量単価"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=4,
                        verbose_name="税率",
                    ),
                ),
                (
                    "tax_rounding_rule",
                    models.CharField(
                        choices=[
                            ("round", "四捨五入"),
                            ("floor", "切り捨て"),
                            ("ceil", "切り上げ"),
                        ],
                        default="floor",
                        max_length=10,
                        verbose_name="端数処理",
                    ),
                ),
                (
                    "invoice_registration_no",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="適格請求書登録番号"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="契約開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="契約終了日"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="core.customer",
                        verbose_name="顧客",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reading_month", models.DateField(verbose_name="検針月")),
                ("current_value", models.PositiveIntegerField(verbose_name="今月指針")),
                (
                    "previous_value",
                    models.PositiveIntegerField(verbose_name="前回指針"),
                ),
                ("usage_amount", models.PositiveIntegerField(verbose_name="使用量")),
                ("measured_at", models.DateField(verbose_name="検針日")),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_readings",
                        to="core.customer",
                        verbose_name="顧客",
                    ),
                ),
                (
                    "input_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="input_meter_readings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="入力担当",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_month", "customer__customer_code"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="請求番号"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="発行日")),
                ("due_date", models.DateField(verbose_name="支払期限")),
                (
                    "base_fee_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本料金"
                    ),
                ),
                (
                    "usage_fee_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="従量料金"
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="税抜合計"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="消費税"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="税込合計"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=4,
                        verbose_name="税率",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "発行済"),
                            ("paid", "入金済"),
                            ("overdue", "期限超過"),
                            ("cancelled", "取消"),
                        ],
                        default="issued",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PDFパス"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.customer",
                        verbose_name="顧客",
                    ),
                ),
                (
                    "meter_reading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="core.meterreading",
                        verbose_name="検針",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "invoice_no"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="入金日")),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="入金額"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=30, verbose_name="入金方法"),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="受領担当"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="参照番号"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.invoice",
                        verbose_name="請求",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(max_length=50, verbose_name="領収書番号"),
                ),
                ("issued_at", models.DateTimeField(verbose_name="発行日時")),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PDFパス"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_issues",
                        to="core.payment",
                        verbose_name="入金",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.UniqueConstraint(
                fields=("customer", "reading_month"), name="uq_customer_reading_month"
            ),
        ),
    ]
