# Generated by Django 5.2.11 on 2026-02-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["customer__customer_code", "-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["customer_code"]},
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "発行済"),
                    ("partial", "一部入金"),
                    ("paid", "入金済"),
                    ("overdue", "期限超過"),
                    ("cancelled", "取消"),
                ],
                default="issued",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="meterreading",
            name="usage_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="使用量"),
        ),
    ]
